# INPUT
input CustomerDataInput {
  email: String!
}

input CustomerIdInput {
  id: ID!
}

input CustomerInput {
  email: String!
  firstName: String!
  lastName: String!
  telephone: String!
  cpf: String!
  password: String!
  date_of_birth: String!
  gender: Int!
}

input CustomerUpdateInput {
  email: String
  firstName: String
  lastName: String
  telephone: String
  cpf: String
  password: String
  date_of_birth: String
  gender: Int
}

input CustomerSignInInput {
  email: String
  password: String
}

# RETURN

type Customer {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  telephone: String!
  cpf: String!
  password: String!
  date_of_birth: String!
  gender: Int!
}

type CreatedCustomer {
  customer: Customer!
}

type DeletedCustomer {
  delete: Boolean!
}

type TokenCustomer {
  token: String!
}

# QUERIES / MUTATIONS

type Query {
  customerList: [Customer!]!
  customer(data: CustomerDataInput!): CreatedCustomer!
  customerInfo(hash: ID!): CreatedCustomer!
}

type Mutation {
  createCustomer(data: CustomerInput!): CreatedCustomer!
  updateCustomer(hash: ID!, data: CustomerUpdateInput!): CreatedCustomer!
  deleteCustomer(email: String!): DeletedCustomer!
  signInCustomer(data: CustomerSignInInput!): TokenCustomer!
}
