version: '3.6'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_db
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PORT=${REDIS_PORT}
